In [ ]:
from utils.misc.parser import parser
from utils.simulation.simulation import simulation

#read config_file
args = parser('config_file.csv')
#create simulation
sim = simulation(**args, verbose=False, addNoise=False)

# run timestep by timestep until the end 
#end = False
#while end == False:
#    end = sim.runOneStep()

import works until here


In [1]:
from utils.controller.VPGInvController import VPGInvController

In [ ]:
from utils.controller.VPGInvController import VPGInvController

time =
VBP =
delayTimer 
device, sess, logger_kwargs=dict(), rl_kwargs=dict()
controller = VPGInvController()

In [ ]:
sim.plot_voltage_at_nodes(nodes=[1,2,3,5,7], height=8, width=15)

In [ ]:
sim.plot_y_at_nodes(nodes=[5,7,10], height=8, width=15)

In [ ]:
sim.plot_VBP_at_nodes(nodes=[5,6,7], height=8, width=15)

In [2]:
import opendssdirect as DSSObj

DSSObj.run_command('Redirect ~/Documents/GitHub/ceds-cigar/LBNL_Simulations/feeders/feeder34_B_NR/feeder34_B_NR.dss')
TotalLoads=DSSObj.Loads.Count()
AllLoadNames=DSSObj.Loads.AllNames()
print(TotalLoads, AllLoadNames)

31 ['dl_82034', 'dl_858m', 'dload_806m', 'dload_810', 'dload_810m', 'dload_822', 'dload_822m', 'dload_824', 'dload_826', 'dload_826m', 'dload_828', 'dload_830', 'dload_830m', 'dload_834', 'dload_836', 'dload_838', 'dload_838m', 'dload_840', 'dload_844', 'dload_846', 'dload_848', 'dload_856', 'dload_856m', 'dload_860', 'dload_864', 'dload_864m', 'sload_840', 'sload_844', 'sload_848', 'sload_860', 'sload_890']


In [46]:
from utils.misc.parser import parser
import pandas as pd
#df = pd.read_csv('config_file.csv')
#df = df.set_index(list(df)[0])
#a = df.loc['logger_kwargs'][0].split(';')[0]

args = parser('config_file.csv')

ValueError: malformed node or string: <_ast.Name object at 0x7f42e84a6320>

In [47]:
df = pd.read_csv('config_file.csv')
df = df.set_index(list(df)[0])
OpenDSSkwargs = {}
for prop in df.loc['logger_kwargs'][0].split(';'):
    try:
        OpenDSSkwargs[prop.split(':')[0].strip(' ')] = ast.literal_eval(prop.split(':')[1].strip(' '))
    except:
        OpenDSSkwargs[prop.split(':')[0].strip(' ')] = prop.split(':')[1].strip(' ')

In [48]:
df.loc['rl_kwargs'][0].split(';')

['hid: 64',
 ' l: 2',
 ' gamma: 0.99',
 ' cpu: 4',
 ' pi_lr: 3e-4 ',
 'vf_lr: 1e-3',
 ' train_v_iters: 80',
 ' lam: 0.97',
 ' save_freq: 10',
 ' buff_size: 5',
 ' activation= tanh',
 ' output_activation: tanh']

In [1]:
from utils.misc.parser import parser
import numpy as np
from utils.simulation.simulation import simulation

args = parser('config_file.csv')
print(args)

sim = simulation(**args, verbose=False, addNoise=False)

for ep in range(2):
    end = False
    while not end:
        end = sim.runOneStep()
    sim.reset()
    print(ep)
 


{'initController': {5: {'type': 'PPOInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'delayTimer': 60}, 6: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 7: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 8: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 9: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 10: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 11: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 12: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.03, 1.05], 'nk': 0.1, 'threshold': 0.25, 'delayTimer': 60}, 13: {'type': 'AdaptiveInvController', 'VBP': [1.01, 1.03, 1.

Early stopping at step 0 due to reaching max kl.
-------------------------------------
|    AverageEpRet |       -3.91e+04 |
|        StdEpRet |               0 |
|        MaxEpRet |       -3.91e+04 |
|        MinEpRet |       -3.91e+04 |
|           EpLen |               5 |
|    AverageVVals |           0.338 |
|        StdVVals |          0.0593 |
|        MaxVVals |           0.429 |
|        MinVVals |           0.265 |
|          LossPi |           0.343 |
|           LossV |        5.95e+08 |
|     DeltaLossPi |         -0.0402 |
|      DeltaLossV |       -5.57e+05 |
|         Entropy |             154 |
|              KL |             159 |
|        ClipFrac |             0.8 |
|        StopIter |               0 |
|            Time |            3.31 |
-------------------------------------
[[1.1359417 1.0306226 1.2017467 0.8939362]]
[[1.0586121 1.0024971 1.2151822 0.8379946]]
[[1.1222036  1.0428327  1.1781876  0.93286246]]
[[1.0300274  1.0407712  1.085633   0.90028125]]
[[1.049

[[1.1174953  0.96436536 1.1168635  0.88048935]]
[[1.0510118  0.98116606 1.0968323  0.9235689 ]]
[[1.0893577  0.99200237 1.056526   0.8872647 ]]
[[1.0524759  1.0427394  1.1210678  0.86339533]]
[[1.0935462 1.0462792 1.1165036 0.945202 ]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  0.9699458 , 143.46288   ,  34.514584  ],
        [  0.96994954, 143.48808   ,  34.57022   ],
        [  0.9699542 , 143.51277   ,  34.625557  ],
        [  0.96995986, 143.53697   ,  34.68058   ],
        [  0.9699664 , 143.5607    ,  34.73527   ],
        [  0.9699739 , 143.58397   ,  34.789616  ],
        [  0.9699824 , 143.60681   ,  34.843597  ],
        [  0.96999174, 143.62923   ,  34.8972    ],
        [  0.97000206, 143.65126   ,  34.95041   ],
        [  0.9700132 , 143.6729    ,  35.00321   ],
        [  0.9700253 , 143.69418   ,  35.055584  ],
        [  0.9700383 , 143.71513   ,  35.107517  ],
        [  0.9700522 , 143.73575   ,  35.158997  ],
        [  0.9700669 , 143.

[[1.0999197  0.98667234 1.0670393  0.9567086 ]]
[[1.0915191  0.94692224 1.0820627  0.8941321 ]]
[[1.081832  1.0210443 1.11557   0.9719056]]
[[1.2925643 1.045992  0.9664162 0.8641643]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  0.9708634 , 146.86496   ,  37.276485  ],
        [  0.9707979 , 146.75444   ,  37.226547  ],
        [  0.97073066, 146.64165   ,  37.173367  ],
        [  0.9706618 , 146.5267    ,  37.117023  ],
        [  0.97059155, 146.40973   ,  37.057602  ],
        [  0.97051984, 146.29083   ,  36.995186  ],
        [  0.9704468 , 146.17014   ,  36.929863  ],
        [  0.9703726 , 146.04776   ,  36.861713  ],
        [  0.97029734, 145.9238    ,  36.790825  ],
        [  0.9702211 , 145.7984    ,  36.717278  ],
        [  0.9701439 , 145.67166   ,  36.641155  ],
        [  0.97006595, 145.54372   ,  36.56255   ],
        [  0.9699873 , 145.41466   ,  36.481533  ],
        [  0.969908  , 145.28462   ,  36.398197  ],
        [  0.96982825, 145.

Load Interpolation has been done. Noise was added to the load profile.
Initial Model Converged. Proceeding to Next Step.
OpenDSS Reset Done.
0
[[1.1595936 1.0212216 1.1383544 1.0081725]]
[[1.1415837 0.9760187 1.077266  0.8444669]]
[[1.1160675  1.0488914  1.1127794  0.88333315]]
[[1.0821439 1.0513368 1.0344906 0.9019335]]
[[1.0666094  1.0497347  1.0736058  0.96122986]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  0.96285814, 142.18321   ,  31.968697  ],
        [  0.96278006, 142.21175   ,  33.283634  ],
        [  1.0612376 , 142.24268   ,  32.092255  ],
        [  1.0617551 , 142.27583   ,  33.39876   ],
        [  1.0618769 , 142.31108   ,  32.921535  ],
        [  0.85758394, 142.3482    ,  32.04293   ],
        [  1.0617541 , 142.38707   ,  32.913914  ],
        [  1.061589  , 142.42749   ,  31.16834   ],
        [  0.9868409 , 142.46931   ,  33.073387  ],
        [  1.0068518 , 142.51236   ,  32.109657  ],
        [  1.0621903 , 142.55647   ,  32.57587  

[[1.1257541 1.055551  1.0649983 0.9621655]]
[[1.2285287 1.0162953 1.1109867 0.9891444]]
[[1.1951786  0.9559514  1.0682927  0.91122735]]
[[1.1412861 1.0164634 0.9555545 0.9134438]]
[[1.1155548  0.98646283 1.0841258  1.059939  ]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  1.0515165 , 138.78069   ,  31.155125  ],
        [  0.89348906, 138.85399   ,  33.550735  ],
        [  0.95696884, 138.92953   ,  32.80775   ],
        [  1.0587988 , 139.00713   ,  33.58196   ],
        [  0.9651573 , 139.08658   ,  30.979359  ],
        [  0.91053265, 139.1677    ,  31.5744    ],
        [  1.0266093 , 139.25027   ,  32.82919   ],
        [  0.97277397, 139.3341    ,  31.680077  ],
        [  0.9303348 , 139.41899   ,  32.2001    ],
        [  0.9810809 , 139.50475   ,  34.00374   ],
        [  1.0295299 , 139.59116   ,  34.830936  ],
        [  0.9288405 , 139.67804   ,  32.418232  ],
        [  0.93885213, 139.76518   ,  33.567093  ],
        [  1.0556341 , 139.85239   

[[1.1360586 1.0689324 1.0871508 1.039475 ]]
[[1.0930173  1.0397615  1.1245562  0.93977547]]
[[1.1728518  1.1121198  1.0793254  0.98100394]]
[[1.0950357 1.0559803 1.0580032 0.9174252]]
[[1.163012   1.0144691  0.98045313 1.0301381 ]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  0.9718442 , 143.46288   ,  35.357048  ],
        [  0.95022696, 143.48808   ,  34.567375  ],
        [  0.95499694, 143.51277   ,  34.682877  ],
        [  0.9606016 , 143.53697   ,  33.889427  ],
        [  0.95911735, 143.5607    ,  36.24678   ],
        [  0.9575375 , 143.58397   ,  34.360413  ],
        [  0.9576996 , 143.60681   ,  34.562107  ],
        [  0.95951456, 143.62923   ,  34.59855   ],
        [  0.95875883, 143.65126   ,  35.921772  ],
        [  0.9578154 , 143.6729    ,  36.169144  ],
        [  0.95815414, 143.69418   ,  34.87108   ],
        [  0.9587547 , 143.71513   ,  35.1141    ],
        [  0.95875216, 143.73575   ,  35.665543  ],
        [  0.9591406 , 143.7560

[[1.1119177  0.97101927 1.0882815  0.9305575 ]]
[[1.1061969  0.98983085 1.0728618  0.96947813]]
[[1.1815729  0.97028214 1.089945   0.99678123]]
[[1.1106186  1.0695335  0.9916229  0.88651437]]
{<tf.Tensor 'Placeholder:0' shape=(?, 60, 3) dtype=float32>: array([[[  0.97357625, 146.86496   ,  37.21738   ],
        [  0.97390723, 146.75444   ,  37.048283  ],
        [  0.97275317, 146.64165   ,  36.501236  ],
        [  0.9739713 , 146.5267    ,  35.659286  ],
        [  0.97299427, 146.40973   ,  36.216072  ],
        [  0.9731    , 146.29083   ,  36.502758  ],
        [  0.9725117 , 146.17014   ,  36.824406  ],
        [  0.9724769 , 146.04776   ,  37.52042   ],
        [  0.97337604, 145.9238    ,  37.418583  ],
        [  0.97258365, 145.7984    ,  36.919983  ],
        [  0.97368646, 145.67166   ,  35.61254   ],
        [  0.97191   , 145.54372   ,  36.762405  ],
        [  0.9719869 , 145.41466   ,  37.138714  ],
        [  0.9729688 , 145.28462   ,  37.088676  ],
        [  0.972419

-------------------------------------
|    AverageEpRet |       -4.05e+04 |
|        StdEpRet |               0 |
|        MaxEpRet |       -4.05e+04 |
|        MinEpRet |       -4.05e+04 |
|           EpLen |               4 |
|    AverageVVals |           -22.9 |
|        StdVVals |          0.0231 |
|        MaxVVals |           -22.8 |
|        MinVVals |           -22.9 |
|          LossPi |         -0.0214 |
|           LossV |             418 |
|     DeltaLossPi |          -0.122 |
|      DeltaLossV |          -0.366 |
|         Entropy |           -6.93 |
|              KL |           0.123 |
|        ClipFrac |             0.6 |
|        StopIter |               7 |
|            Time |              88 |
-------------------------------------

Simulation Done!

Starting Interpolation...
Load Interpolation has been done. Noise was added to the load profile.
Initial Model Converged. Proceeding to Next Step.
OpenDSS Reset Done.
1


In [10]:
sim.inverters[5][0]['controller'].action

array([[1.1106186 , 1.0695335 , 0.9916229 , 0.88651437]], dtype=float32)